version: '3'
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true
services:
    
    metabase:
      image: metabase/metabase
      container_name: ${PROJECT_NAME}-metabase
      ports:
        - ${METABASE_PORT}:3000
      env_file:
      - .env  