version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true

services:
  jupyterlab:
    image: jupyterlab
    container_name: ${PROJECT_NAME}-jupyterlab
    ports:
      - ${JUPYTERLAB_PORT}:8888
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - .env

  spark-master:
    image: spark-master
    container_name: ${PROJECT_NAME}-spark-master
    environment:
      SPARK_LOCAL_IP: 'spark-master'
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - .env

  spark-worker-1:
    image: spark-worker
    container_name: ${PROJECT_NAME}-spark-worker-1
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    env_file:
      - .env  
  spark-worker-2:
    image: spark-worker
    container_name: ${PROJECT_NAME}-spark-worker-2
    environment:
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    ports:
      - 8084:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    env_file:
      - .env  